### ISSUE TITLE
Raspberry pi and cyclone10 board

### ISSUE THREAD

**Issue by CrackenDesigns** [trabucayre/openFPGALoader#74] opened 2021-01-31 14:55 UTC
Hi, I got a cyc1000 from Trenz attached to a raspberry pi 3 and tried your soft to send .svf files. After compiling and installing I can flash the test file sucesfully but at the end of the command the error "detach error -5" appears always. The test file seems to work  but all my generated cores with quartus doesn´t work, looks like the flashing is correct but always get "end of flash" followed by the "detach error -5". Any clue of this?

Thanks.

**Comment by trabucayre** [comment] 2021-01-31 15:10
Hi,
the "detach error -5" is unfortunatly normal. the FTDI interface is configured as jtag, and, consequently, the driver didn't attach this.
At the beginning, openFPGALoader detact the driver and a the end try to reattach the device, but this fails because the reattach can't be done in this situation.
Anyway if "end of flash" is shown it's okay, the bitstream is correctly loaded.

**Comment by CrackenDesigns** [comment] 2021-01-31 15:36
Hi, thanks for your reply. It looks like the bitstream is ok but doesn´t work, the board gets like if you just powered up. Of course these .svf are tested programming with the quartus programmer. Compared your test file with mine and they have the same header and end of file.

Thanks.
________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: domingo, 31 de enero de 2021 15:10
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


Hi,
the "detach error -5" is unfortunatly normal. the FTDI interface is configured as jtag, and, consequently, the driver didn't attach this.
At the beginning, openFPGALoader detact the driver and a the end try to reattach the device, but this fails because the reattach can't be done in this situation.
Anyway if "end of flash" is shown it's okay, the bitstream is correctly loaded.

**Comment by trabucayre** [comment] 2021-01-31 15:48
The design works when programmed with quartus but didn't work with openFPGALoader?
If true it's weird because with svf, the task is to do is to follows instructions contained in the file.
The only main difference is: quartus use sof to load bitstream instead of svf.

**Comment by CrackenDesigns** [comment] 2021-01-31 15:54
Yes, it doesn´t work neither in some boards like banana pi, raspi and even with my laptop with ubuntu.
Your test file takes a little bit more time to flash than my files.
________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: domingo, 31 de enero de 2021 15:48
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


The design works when programmed with quartus but didn't work with openFPGALoader?
If true it's weird because with svf, the task is to do is to follows instructions contained in the file.
The only main difference is: quartus use sof to load bitstream instead of svf.

**Comment by trabucayre** [comment] 2021-01-31 16:03
Really weird. I, currently, works with my cyc1000 without issue. Which quartus version you use ?
when you talk about test file it's test_svf.svf (in fact it's a bridge to access eeprom through ftdi interfaceB).
Could you copy command you use to generate svf file ?
Thanks

**Comment by CrackenDesigns** [comment] 2021-01-31 16:20
I use the quartus programmer to generate the .svf file. The strange thing is that this .svf works without problem using urjtag svf command. Attached is the one I´m using.

________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: domingo, 31 de enero de 2021 16:03
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


Really weird. I, currently, works with my cyc1000 without issue. Which quartus version you use ?
when you talk about test file it's test_svf.svf (in fact it's a bridge to access eeprom through ftdi interfaceB).
Could you copy command you use to generate svf file ?
Thanks

**Comment by trabucayre** [comment] 2021-01-31 16:30
Ok. I convert the svf using cli:
```bash
quartus_cpf -c -q 12.0MHz -g 3.3 -n p file.sof file.svf
```

I'm unable to find your attached file...

**Comment by CrackenDesigns** [comment] 2021-01-31 16:45
Good news, looks like with the quartus .svf generator doesn´t work with openFPGAloader, urjtag works, but using the command line to covert does the trick and now works perfect.

Thanks for your help, I appreciate so much.
________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: domingo, 31 de enero de 2021 16:30
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


Ok. I convert the svf using cli:

quartus_cpf -c -q 12.0MHz -g 3.3 -n p file.sof file.svf

I'm unable to find your attached file...

**Comment by trabucayre** [comment] 2021-01-31 16:51
Perfect!
I need to see the svf built by the GUI. If it's not works this mean something is wrong/missing in the svf Parser....
could you share your svf?

Thanks

**Comment by CrackenDesigns** [comment] 2021-01-31 17:00
Yes, of course I can share, just only testing for an addon we are working on for the cyc1000.
If you have telegram you can reach me @nabateo

Greetings.
________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: domingo, 31 de enero de 2021 16:51
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


Perfect!
I need to see the svf built by the GUI. If it's not works this mean something is wrong/missing in the svf Parser....
could you share your svf?

Thanks

**Comment by trabucayre** [comment] 2021-02-06 05:46
No sorry I haven't telegram.
It's however possible to attach a file to an issue. Is it possible to have access to the svf generated by quartus (not working) and the one from CLI (working).
I have tried to do this with one of my designs but files are identical...
Thanks

**Comment by CrackenDesigns** [comment] 2021-02-06 08:27
Wells I discovered that the files generated  by quartus for windows doesn't work. If you generate with the Linux version works like a charm, weird thing, isn't it?

Regards.

________________________________

**Comment by trabucayre** [comment] 2021-02-06 10:16
Interresting! And maybe less weird as you think.
Windows usually use CRLN (\r\n) instead of LN (\n).
Consequently the '\r' is maybe left in buffer.
Again, can you provide one working file and one not working to check my assumption.
Thanks

**Comment by CrackenDesigns** [comment] 2021-02-06 11:35
Hi, here we go...
As I said, each one is generated with quartus for windows and quartus for linux.

Regards.
________________________________
De: Gwenhael Goavec-Merou <notifications@github.com>
Enviado: sábado, 6 de febrero de 2021 10:16
Para: trabucayre/openFPGALoader <openFPGALoader@noreply.github.com>
Cc: CrackenDesigns <ministrodelaire@msn.com>; Author <author@noreply.github.com>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


Interresting! And maybe less weird as you think.
Windows usually use CRLN (\r\n) instead of LN (\n).
Consequently the '\r' is maybe left in buffer.
Again, can you provide one working file and one not working to check my assumption.
Thanks

**Comment by trabucayre** [comment] 2021-02-06 14:42
Hi,
my problem is I have only linux computers, so I have no way to generate an svf with quartus for windows :-(

**Comment by trabucayre** [comment] 2021-02-08 05:35
Hi,
With the help of `unix2dos` utility I have converted an svf file, this file has confirmed the issue with CRLN format.
Now fixed.
Could you retry to confirm it's okay for you?

Thanks

**Comment by trabucayre** [comment] 2021-07-23 05:31
It's okay for you ?

**Comment by CrackenDesigns** [comment] 2021-07-26 10:07
Hi mate, it´s ok now, Good job, thanks.

De: Gwenhael ***@***.***>
Enviado: viernes, 23 de julio de 2021 7:31
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [trabucayre/openFPGALoader] Raspberry pi and cyclone10 board (#74)


It's okay for you ?

**Comment by trabucayre** [comment] 2021-07-26 10:13
Thanks

**Closed by trabucayre** 2021-07-26 10:13 UTC
